name: Ejecutar tests automáticos

on:
  push:
    branches: [ "main", "Modulo-de-urgencias" ]
  pull_request:
    branches: [ "main", "Modulo-de-urgencias"  ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ingsw-app   

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Compilar y ejecutar tests
        run: mvn -B clean verify

      - name: Listar archivos generados
        if: always()
        run: |
          ls -la
          ls -la target || true
          find target -maxdepth=3 -type f -print || true

      - name: Publicar reportes (Cucumber + Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/cucumber-reports/**
            target/**/cucumber*.json
            target/**/cucumber*.xml
            target/**/cucumber*.html
            target/surefire-reports/**
            target/failsafe-reports/**
          if-no-files-found: warn
